from chess.piece.exceptions import PieceValidationError


class PawnValidationError(PieceValidationError):
    pass

