from chess.exceptions import ValidationError


class PieceValidationError(ValidationError):
    pass

